name: Generate Graph  
on: [push]  
  
jobs:  
 build:  
   runs-on: ubuntu-latest  
   steps:  
   - uses: actions/checkout@v4  
  
   - name: Setup Node.js  
     uses: actions/setup-node@v4  
     with:  
       node-version: '20'  
  
   - name: Install dependencies  
     run: npm install remark unist-util-visit  
  
   - name: Generate graph data  
     run: node scripts/generate-graph.js  
  
   - name: Commit changes  
     run: |  
       git config user.name "GitHub Bot"  
       git config user.email "bot@noreply.github.com"  
       git add docs/graph.json  
       git commit -m "Update graph data" || echo "No changes to commit"  
       git push  
